name: "multi event pipeline/ workflow"

on:
    push: 
        branches:
            - master

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on a Master push"
                run: echo"Running on master push"

